# training for SR1 + VBF veto Region

train:
    model_name: "bbll_pdnn_sr1"
    model_class: "Model_Sequential_Flat"
    use_multi_label: true
    layers: 5
    nodes: 256
    dropout_rate: 0
    momentum: 0.5
    nesterov: true
    test_rate: .2
    val_split: .25
    #k_folds: 5
    learn_rate: 0.1
    learn_rate_decay: 0.02
    batch_size: 512
    epochs: 50
    train_metrics_weighted:
        - "accuracy"
        - "auc"

    # early stop setups
    use_early_stop: true
    early_stop_paras:
        monitor: "val_loss"
        min_delta: 0.0001
        patience: 5
        mode: "min"
        restore_best_weights: true

    # save model or not
    save_model: true

    verbose: 1